#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
# programmed by Hiroshi Kimura, 2012-04-22.
#
# 本日の gtypist のスコアを表示する学生向けスクリプト。
#

DEBUG=false
GTYPIST_HOME="/home/t/hkimura/literacy/gtypist"

def debug(s)
  puts "debug: "+s if DEBUG
end

M={"Jan"=>"01", "Feb"=>"02", "Mar"=>"03", "Apr"=>"04",
   "May"=>"05", "Jun"=>"06", "Jul"=>"07", "Aug"=>"08",
   "Sep"=>"09", "Oct"=>"10","Nov"=>"11","Dec"=>"12"}

#
# main starts here.
#
home=GTYPIST_HOME
uid=ENV['USER']
while (arg=ARGV.shift)
  case arg
  when /\A--gtypist/
    home=ARGV.shift
  when /\A--uid/
    uid=ARGV.shift
  else
    raise "unknown option: #{arg}"
  end
end

begin
  fname=File.join(home,uid)
  raise "記録が見つかりません。#{fname}" unless File.exists?(fname)
  flag=cleared=rate=nil
  results=Array.new
  IO.readlines(fname).reverse.each do |line|
    debug line
    wday,month,date,time,year,rest=line.chomp.split(/\s/,6)
    if flag
      next unless rest=~/^\*:(.*)$/
      score=$1
      results.push "#{cleared} #{score}" if score=~/_.+_.+_/
      flag=cleared=rate=nil
    else
      if rest=~/^with (\d)\.(\d)% errors/
        rate="#{$1}.#{$2}".to_f
        if rate < 3.0
          cleared="#{year}-#{M[month]}-#{date} #{time}"
          flag=true
        end
      end
    end
  end

  puts results.reverse.join("\n")

rescue =>e
  puts e.message
end